### ISSUE TITLE
[Feature] - 스타일, 정적 파일 초기 셋팅

### ISSUE THREAD

**Issue by yws1502** [yws1502/canipay-fe#1]
### Description
- 프로젝트에서 사용되는 색상 코드, 폰트 설정 작업을 수행합니다.

### TO-DO
- [x] 색상 코드 설정 (Tailwind CSS config 적용)
- [x] 폰트 설정 (Tailwind CSS config 적용)
- [x] 정적 파일 추가
- [x] Favicon,head title 변경

### Note
- [canipay 피그마](https://www.figma.com/design/OTiqgyZbELFfnfgShK8EkV/Can-I-Pay?node-id=0-1&node-type=canvas&t=DEJMcT4G5qBSpOUq-0)를 참고하여 색상 코드를 설정합니다.
<img width="938" alt="image" src="https://github.com/user-attachments/assets/b0c085ca-ca42-4090-b031-8feafe222f4c" />

![image](https://github.com/user-attachments/assets/23ea80cb-71e1-4d08-bc5d-98da623e4cae)
