### ISSUE TITLE
[Feature] - 설정 페이지 개발

### ISSUE THREAD

**Issue by yws1502** [yws1502/canipay-fe#12]
### Description
- 서비스의 사용자 설정 및 서비스 정보를 표출하는 페이지입니다.
- 사용자 설정
     - 글자 크기, 테마 설정
- 서비스 정보
    - 문의 사항, 버전 정보, 공지사항, 오픈소스 라이선스 이용고지

### TO-DO
- [x] 설정 페이지 Markup & Styling
- [x] 글자 크기 설정
- [ ] ~~다크 테마 설정~~ -> 해당 기능은 추후 별도 이슈에서 처리할 예정입니다.
- [x] 버전 정보 클릭 시 Github release note로 새로운 창 열기
- [x] 오픈소스 라이선스 이용 고지 페이지 개발

### Note
<img width="316" alt="image" src="https://github.com/user-attachments/assets/8c4534d0-e4de-471a-9dda-f92781d8438f" />
