### ISSUE TITLE
[Feature] - 지역 검색 기능 개발

### ISSUE THREAD

**Issue by yws1502** [yws1502/canipay-fe#4]
### Description
- TMAP의 지역 검색 API를 활용한 검색 기능을 개발합니다.
- 검색 결과는 지도에 마커로 표시됩니다.
    - 추후 매장 목록 컴포넌트 개발 시 결과 목록 개발 예정 (#5)
    - hover, click 이벤트 시 Modal 띄워지는 기능 추후 개발 예정 (#5)
- 검색 페이지 이탈을 원할 시 입력창 좌측에 X 버튼을 클릭합니다.
- 검색어 수정을 원하는 경우 검색 입력창을 클릭합니다. (focus)

### TO-DO
- [x] TMAP 지역 검색 API 연동 -> 추후 Forward Proxy를 활용하여 인증키 노출 방지
- [x] 지도에 마커 표시

### Note
<img width="316" alt="image" src="https://github.com/user-attachments/assets/a41d7a7f-5131-410c-a7f9-fe71af315fcc" />

- 추후 작업 리스트 
- [x] 결과 목록 추가
- [x] 마커 hover, click 이벤트 추가
- [ ] TMAP API 요청 Forward Proxy 설정
