### ISSUE TITLE
[Feature] - 매장 목록 컴포넌트 개발

### ISSUE THREAD

**Issue by yws1502** [yws1502/canipay-fe#5]
### Description
- 검색, 주변 검색, 지도(Modal), 목록 페이지에서 공용으로 사용되는 컴포넌트를 개발합니다.
- 카테고리 별 필터 기능을 제공합니다.
- 목록의 높이 조절 기능을 제공합니다.
- 목록 아이템의 버튼 별 action은 아래와 같습니다.
    - 타이틀 클릭 시 상세 페이지 이동
    - 네이버 버튼 클릭 시 네이버 지도로 새로운 창 열기
    - 주소 버튼 클릭 시 주소 복사
    - 전화번호 클릭 시 번호 복사
    - 아이템 영역 중 위에 해당하지 않는 영역 클릭 시 지도 위치 재조정 (해당 매장 위치로 이동)
- #4 이슈의 검색 페이지에 해당 컴포넌트 적용

### TO-DO
- [x] 매장 데이터 Markup & Styling
- [x] 컴포넌트 높이 조절 기능 개발
- [x] 무한 스크롤 가능하도록 개발
- [x] 버튼 별 action 처리

### Note
<img width="330" alt="image" src="https://github.com/user-attachments/assets/c2282bfd-c3b9-44dc-9d2f-8b0d198de4b5" />

### 추후 개발
- [ ] 카테고리 별 필터 기능 개발
