### ISSUE TITLE
[Feature] - 상세 페이지 (매장 등록) 개발

### ISSUE THREAD

**Issue by yws1502** [yws1502/canipay-fe#7]
### Description
- 해당 기능을 구현하기 위해선 백엔드 서버 구현이 선행되어야 합니다.
- 등록되지 않은 매장인 경우 렌더링되는 페이지입니다.
- 해당 페이지에서 매장을 등록할 수 있습니다. (결제 가능 / 불가능 여부 설정)

### TO-DO
- [x] 상세 페이지 Markup & Styling
- [x] 상세 페이지의 버튼 별 action은 아래와 같습니다.
    - 네이버 버튼 클릭 시 네이버 지도로 새로운 창 열기
    - 주소 버튼 클릭 시 주소 복사
    - X 버튼 클릭 시 이전 페이지로 이동
    - 매장 등록 버튼 (결제 가능, 결제 불가능) -> 백엔드 POST API
- [x] 상세 데이터 호출 시 에러가 발생하는 경우 에러 페이지 개발

### Note
<img width="396" alt="image" src="https://github.com/user-attachments/assets/ca99cc7c-b668-4229-b9d0-965ee0588235" />
