### ISSUE TITLE
[Feature] - 지도 페이지 모달 기능 및 마커 토글 기능 개발

### ISSUE THREAD

**Issue by yws1502** [yws1502/canipay-fe#9]
### Description
- 지도 페이지의 마커 hover, click 시 표출되는 모달을 개발합니다.
- #5 컴포넌트를 활용합니다.
- 마커를 토글하여 키고 끌 수 있는 기능을 제공합니다.

### TO-DO
- [x] #5 컴포넌트를 활용한 모달 개발
- [x] 지도 마커 hover, click 이벤트 적용
- [x] 마커 토글 기능 개발

### Note
<img width="340" alt="image" src="https://github.com/user-attachments/assets/37cacd55-2ca8-4150-914f-f4e3d3364143" />
